### ISSUE TITLE
'AppTrackingTransparency/AppTrackingTransparency.h' file not found

### ISSUE THREAD

**Issue by cheabkunthea** [tomitank/cordova-plugin-admob-tomitank#1]
Hello,

When build app, I got error 'AppTrackingTransparency/AppTrackingTransparency.h' file not found.
Please help.
 Thank you

**Comment by cauboy** [comment]
Hey @cheabkunthea, I've had the same issue. After upgrading to the latest version of XCode  (>=12) the issue was resolved.
