### ISSUE TITLE
Is this how to make a consent popup?

### ISSUE THREAD

**Issue by DesignerApparelSales** [tomitank/cordova-plugin-admob-tomitank#10]
Hi, I never have seen that consent popup before, So I'm not sure how it should look like. 

So at the beginning of the app, I make a pop up saiding , " There is no personal Ads in this app, We do not take any of your personal data."   ??
 and I should have this " adExtras: { npa: '1' }"  in your code? Is that how to do it? Or do I don't even need to add  "adExtras: { npa: '1' }"   I don't think I ever seen plugin-admob-free display a have personal ads before. So is that even necessary?  Thanks in advance

 this.admob.interstitial.config({
                    adExtras: { npa: '1' } //we send the "npa" flag set to '1' to request non personalized ads
                });

**Comment by tomitank** [comment]
you don't even need to add adExtras
