### ISSUE TITLE
App rejected in the Apple Store with Reason. - Dialogue is not displayed again after uninstalling and installing the App

### ISSUE THREAD

**Issue by 123dma** [tomitank/cordova-plugin-admob-tomitank#11]
Hello I had the App rejected in the Apple Store with Reason.

Guideline 2.1 - Information Needed

We're looking forward to completing the review of your app, but we need more information to continue. Specifically, we noticed that your app uses the AppTrackingTransparency framework, but we haven't been able to locate the relevant AppTrackingTransparency permission requests.

While it is not required to implement AppTrackingTransparency at this time, we check to make sure the implementation is compliant with our guidelines when we detect the framework in an app.

Next Steps

If your app integrates AppTrackingTransparency, please indicate where in your app we can find the AppTrackingTransparency permission request.

If your app does not integrate AppTrackingTransparency, please indicate this information in the Review Notes section for each version of your app in App Store Connect when submitting for review.

Resources
See the app privacy question update.
Learn more about how AppTrackingTransparency protects user's privacy and data.

--------------------------------

I did everything right and tested it correctly, but I noticed that after uninstalling the App and installing it again, admob.trackingStatusForm (). Then (function (status) {} no longer presents the request dialog. Keeping the last answer given by I believe it is a bug and this is the problem.

I tested it on the emulator, the dialog is not displayed again as long as I accept a first time. When the application is uninstalled and installed again, it is no longer displayed. 
Status does not return to NotDetermined

**Comment by vincom-dev** [comment]
in my app sone situation ... its a problem ? about secont time ,?
