### ISSUE TITLE
call interstitial another time?

### ISSUE THREAD

**Issue by matrixreal** [tomitank/cordova-plugin-admob-tomitank#12]
Hello,
Thanks for your plugin
i use your simplified code in the app start (device ready):
`                       admob.interstitial.config({ id: admobid.interstitial, isTesting: false, autoShow: false });

			admob.banner.config({ id: admobid.banner, overlap: true, isTesting: false, autoShow: true });

			admob.getTrackingStatus().then(function(status) {

				if (status == 'notDetermined') {

					navigator.notification.confirm(LANGUAGE.tracking_info_msg, function() {

						admob.trackingStatusForm().then(function(status) {

							admob.banner.prepare(); // autoShow..

							admob.interstitial.prepare().then(function() {
								admob.interstitial.show();
							});
						});

					}, LANGUAGE.tracking_info, [LANGUAGE.okay]);

				} else {

					admob.banner.prepare(); // autoShow..

					admob.interstitial.prepare().then(function() {
						admob.interstitial.show();
					});

					if (status != 'authorized') {
						notification_confirm(LANGUAGE.tracking_error, LANGUAGE.tracking_error_msg, [LANGUAGE.close], null);
					}
				}
			})`

it shows the banner and the interstitials as well.
let's suppose that later in the app (like in a game in the next level) i want to show another interstitial.
do i need to just call admob.interstitial.prepare().then(function() {admob.interstitial.show(); ? or i must ask again user for getTrackingStatus()?
i mean after an app lunch does it save the tracking status unless you close the app?
Thanks

**Comment by tomitank** [comment]
Hi!
you need to just call admob.interstitial.prepare().then(function() {admob.interstitial.show();
