### ISSUE TITLE
Consent feature is not implemented for android

### ISSUE THREAD

**Issue by ptrahan** [tomitank/cordova-plugin-admob-tomitank#13]
Hi, looking at the code, it seems that for android the consent feature is not implemented. It just returns "authorized". Any plans on implementing it for android? Furthermore, could you explain why the Google UMP sdk method is not recommended? What is the issue with it?
Thanks

**Comment by tomitank** [comment]
Maybe I'll add it later.
The Google UMP problem is, that you can only set one language.
