### ISSUE TITLE
IMPORTANT: reward ad no longer available!

### ISSUE THREAD

**Issue by kosbar** [tomitank/cordova-plugin-admob-tomitank#16]
Interesting why?

**Comment by kosbar** [comment]
https://developers.google.com/admob/ios/migration#fullscreen
"Starting with version 8.0.0, interstitial and rewarded ads share a generic full screen ad style for more consistency."

**Comment by tomitank** [comment]
Sorry, i don't use it. If you want to use please make a new branch and push this for me.
