### ISSUE TITLE
Update Admob SDK

### ISSUE THREAD

**Issue by martijnmichel** [tomitank/cordova-plugin-admob-tomitank#17]
Some of your iOS apps require a GMA SDK update To keep ads serving normally and minimize a loss in ad revenue, implement the GMA SDK 7.64.0 (or later) for your iOS apps. And configure the SKAdNetwork in your apps with Google's network ID.

Some apps haven't been configured to use Apple's SKAdNetwork To ensure you're getting credit for all ads activity, like app installs, be sure to configure SKAdNetwork with Google's network IDs.

I saw you've updated the sdk in the repo, when can we use it?

**Comment by vincom-dev** [comment]
i interesed too .

**Comment by tomitank** [comment]
@martijnmichel 
You can use it now.
You need to add the following to config.xml for iOS:
```
		<config-file platform="ios" target="*-Info.plist" parent="SKAdNetworkItems">
			  <array>
    			<dict>
					<key>SKAdNetworkIdentifier</key>
					<string>cstr6suwn9.skadnetwork</string>
				</dict>
			</array>
		</config-file>
```
