### ISSUE TITLE
Update pod Google-Mobile-Ads-SDK spec to 8.4.0 to fix firebasex plugin conflict

### ISSUE THREAD

**Issue by rideo-eduardmorales** [tomitank/cordova-plugin-admob-tomitank#18]
Current spec 8.1.0 throws error with firebasex plugin v.12.1

Updating plugin.xml to:
```
<pod name="Google-Mobile-Ads-SDK" spec="~> 8.4.0" />
```

Solves the issue.

**Comment by svzi** [comment]
@rideo-eduardmorales Just make a PR?! @tomitank will probably happy to merge it.

**Comment by tomitank** [comment]
@rideo-eduardmorales updated! Thanks!
