### ISSUE TITLE
uninstall plugin

### ISSUE THREAD

**Issue by gatelli** [tomitank/cordova-plugin-admob-tomitank#19]
Hi,
I have uninstalled this plugin, but Apple still rejects my app because it doesn't show the transparency dialog.
How can I properly uninstall this, with all ads dependencies, so as Apple can't find any tracking library or functions in the app ?
(Appstore says my app contains **NSUserTrackingUsageDescription** but I can't find any trace in plist or anywhere)

Thanks for your help !

**Comment by tomitank** [comment]
@gatelli  maybe it's in config.xml?

**Comment by gatelli** [comment]
No I removed that. That's weird.

**Comment by tomitank** [comment]
I don't think the plugin is the reason. There was probably something left in the project.
