### ISSUE TITLE
When to show ads?

### ISSUE THREAD

**Issue by svzi** [tomitank/cordova-plugin-admob-tomitank#2]
Could you please explain your provided code sample a little bit more?

```
admob.trackingStatusForm().then(function(status) { // iOS tracking form..
    // show ads..

    if (status != 'authorized') { 
        // not authorized show a motivation popup.. (optional)
        // navigator.notification.confirm..
    }
});
```
Does this mean we should show ads even when `status != 'authorized'`? If not, then maybe you should re-write the code sample, to make it more clear like this:
```
admob.trackingStatusForm().then(function(status) { // iOS tracking form..
    if (status != 'authorized') { 
        // not authorized show a motivation popup.. (optional)
        // navigator.notification.confirm..
    } else {
       // show ads..
    }
});
```

Your feedback would be really much appreciated @tomitank !

**Comment by tomitank** [comment]
> Does this mean we should show ads even when status != 'authorized'?

Yes. We show ads in every case. iOS handle the IDFA authorization in background. (Depending on the decision)

**Comment by svzi** [comment]
Many thanks for the explanation!

**Comment by svzi** [comment]
I'm sorry, but I need to reopen this issue. :-( 

 > if (status != 'authorized') then iOS don't show personalized ads, and we get less money.

I'm testing this on iOS 14 for some days now, but I have some trouble with the `admob.trackingStatusForm()` function. When  `status !== 'authorized'` no banner or interstitials will be served (with `isTesting: true`). When I delete the app from my device, reinstall it and select to authorize the usage of my IDFA, then test-ads will be served.

**Comment by tomitank** [comment]
@svzi 
Did you tryed with this code?
admob.trackingStatusForm().then(function(status) { // iOS tracking form..
    // show ads..

    if (status != 'authorized') { 
        // not authorized show a motivation popup.. (optional)
        // navigator.notification.confirm..
    }
});
I don't tested with test ads. Maybe it's work differently.
I think, the plugin is okay, because of its work perfectly in my app in every case:
iOS: https://apps.apple.com/us/app/sakk/id1150654415
Android: https://play.google.com/store/apps/details?id=sakk.tanky.hu

Please post your ads code here. I'll be check.

**Comment by svzi** [comment]
Yes, I'm using the code from your `README.md`. And this is running when the app starts:

```
this.trackingStatus = await admob.getTrackingStatus(); // get status..
console.log('this.trackingStatus: ' + this.trackingStatus);
```

This is how I show a banner:
```
public async showBanner() {
    console.log('showBanner(), trackingStatus: ' + this.trackingStatus);
    if (this.trackingStatus !== 'authorized') {
        admob.banner.config({
            id: 'ca-app-pub-123',
            isTesting: true,
            adExtras: { npa: '1' }, // we send the "npa" flag set to '1' to request non personalized ads
        });
    } else {
        admob.banner.config({
            id: this.platform.is('ios')
                ? 'ca-app-pub-123',
            isTesting: true,
            adExtras: {}, // we clear the extras flag
        });
    }

    const id: string = await admob.banner.prepare();
    console.log('showBanner(), id: ' + id);
    return admob.banner.show(id);
}
```

This is how the banner looks like, when I authorize the usage of the IDFA:
![IMG_0546](https://user-images.githubusercontent.com/1890513/96350735-6127f400-10b7-11eb-88ed-472a3d8d140c.PNG)

And this is how the banner looks like, when I decline the authorization (see the blank white area where the banner should be):
![IMG_0545](https://user-images.githubusercontent.com/1890513/96350756-7ef55900-10b7-11eb-80bc-fffbd8b4e78f.PNG)

Any ideas @tomitank ?

**Comment by tomitank** [comment]
```
public async showBanner() {
    console.log('showBanner(), trackingStatus: ' + this.trackingStatus);
    admob.banner.config({
        id: this.platform.is('ios')
            ? 'ca-app-pub-1180289214805144/3195758452'
            : 'ca-app-pub-1180289214805144/3716514192',
        isTesting: true,
    });

    const id: string = await admob.banner.prepare();
    console.log('showBanner(), id: ' + id);
    return admob.banner.show(id);
}
```
try change to:
```
public async showBanner() {
    if (first_call) {
        console.log('showBanner(), trackingStatus: ' + this.trackingStatus);
        admob.banner.config({
            id: this.platform.is('ios')
                ? 'ca-app-pub-1180289214805144/3195758452'
                : 'ca-app-pub-1180289214805144/3716514192',
            isTesting: true,
            autoShow: true // show with prepare
        });
        const id: string = await admob.banner.prepare();
        console.log('showBanner(), id: ' + id);
    }
    else 
    {
        return admob.banner.show();
    }
}
```

**Comment by svzi** [comment]
@tomitank Thanks for your feedback but I honestly don't understand what it should change. Keep in mind that the banner shows neither the first nor any other time I hit the button when I select to not authorize. And vice versa when I select to authorize it shows every time. So I doubt your change will have any affect.

I've just changed the code accordingly, to call config and prepare only once (I did so during device ready event). But, as expected, that didn't change anything. I also tried to remove the `isTesting: true` property, but it didn't change anything as well...

Do you test the ads directly via CLI / XCode install on your device or do you test the ads only via TestFlight or when downloaded from the app store?

**Comment by tomitank** [comment]
> Do you test the ads directly via CLI / XCode install on your device or do you test the ads only via TestFlight or when downloaded from the app store?

I tested with xCode 12 simulator and on in my application as well :)
iOS: https://apps.apple.com/us/app/sakk/id1150654415
Android: https://play.google.com/store/apps/details?id=sakk.tanky.hu

**Comment by tomitank** [comment]
Please use the new version and read the new readme.

**Comment by svzi** [comment]
@tomitank Which new version? Do you mean `4.1.0`?
