### ISSUE TITLE
Using AppTrackingTransparency module

### ISSUE THREAD

**Issue by rideo-eduardmorales** [tomitank/cordova-plugin-admob-tomitank#20]
We are implementing this module as described on your README. After trackingStatusForm(), do we have to add the adExtras like we saw in a comment from rastafan:

```
this.admob.interstitial.config({
                    adExtras: { npa: '1' } //we send the "npa" flag set to '1' to request non personalized ads
                });
```

We didn't find any reference on how to do in the README.

Thanks

**Comment by tomitank** [comment]
You don't need to send extra flag. iOS saved your choose.
