### ISSUE TITLE
The event admob.interstitial.events.CLOSE is never fired

### ISSUE THREAD

**Issue by sergip76** [tomitank/cordova-plugin-admob-tomitank#22]
I try to use the event admob.interstitial.events.CLOSE in order to do something after the interstitial video is closed by user, but this event is never fired.
I tried it with Android and iOS and both fails.
On the other hand, the event admob.interstitial.events.LOAD works correctly and it is fired without any problem.

I use this code:

```
document.addEventListener('admob.interstitial.events.CLOSE', (event) => {

        //Someting to do

});
```

**Comment by tomitank** [comment]
Hi!
I use this events without any error:```

			document.addEventListener('admob.banner.events.LOAD', function(e) { 
				admob.banner.ready = true;
			});
			document.addEventListener('admob.banner.events.LOAD_FAIL', function(e) {
				admob.banner.ready = false;
				admob.banner.is_on = false;
			});
			document.addEventListener('admob.interstitial.events.LOAD', function(e) {
				admob.interstitial.ready = true;
			});
			document.addEventListener('admob.interstitial.events.LOAD_FAIL', function(e) {
				admob.interstitial.ready = false;
			});
			document.addEventListener('admob.interstitial.events.OPEN', function(e) {
				hideBanner();
			});
			document.addEventListener('admob.interstitial.events.CLOSE', function(e) {
				showBanner();
			});
```
