### ISSUE TITLE
Failing to load ads without reason

### ISSUE THREAD

**Issue by ciaoben** [tomitank/cordova-plugin-admob-tomitank#4]
I am trying this simple setup

```
      admob.rewardvideo.config({
        id: 'ca-app-pub-xxxxxxxxxxxxxxxxxxxxxx',
        isTesting: false,
        autoShow: true
      });

      document.addEventListener('admob.rewardvideo.events.LOAD', event => {
        console.log('admob.reward_video.LOAD', JSON.stringify(event));
      });

      document.addEventListener('admob.rewardvideo.events.LOAD_FAIL', event => {
        console.log('admob.reward_video.LOAD_FAIL', JSON.stringify(event));
      });

      document.addEventListener('admob.rewardvideo.events.OPEN', event => {
        console.log('admob.reward_video.OPEN', JSON.stringify(event));
      });

      document.addEventListener('admob.rewardvideo.events.CLOSE', event => {
        console.log('admob.reward_video.CLOSE', JSON.stringify(event));
      });

      document.addEventListener('admob.rewardvideo.events.EXIT_APP', event => {
        console.log('admob.reward_video.EXIT_APP', JSON.stringify(event));
      });

      document.addEventListener('admob.rewardvideo.events.START', event => {
        console.log('admob.reward_video.START', JSON.stringify(event));
      });

      document.addEventListener('admob.rewardvideo.events.REWARD', event => {
        console.log('admob.reward_video.REWARD', JSON.stringify(event));
      });

      console.log('ciaoo', JSON.stringify(admob.rewardvideo));

      admob.rewardvideo.prepare();

```

But I keep getting: 
```
admob.reward_video.LOAD_FAIL {"isTrusted":false,"error":"(null)","adType":"rewardvideo"} 
```
How can I get the real reason for the error?

**Comment by rastafan** [comment]
Looks like it may be the same issue i had here: #3 

Please check if you have the "Allow apps to request to track" turned off. 
The option can be enabled or disabled as shown [here](https://9to5mac.com/2020/07/17/allow-block-iphone-app-tracking-ios-14/)

**Comment by tomitank** [comment]
@ciaoben 
You added the ADMOB_APP_ID to config.xml?
```
	<plugin name="cordova-plugin-admob-tomitank" source="npm" spec="*">
		<variable name="ADMOB_APP_ID" value="ca-app-pub-xxxxxxxxxxxxx~xxxxxxxxxxx" />
	</plugin>
```

This example still use "didFailToLoadWithError":
https://developers.google.com/admob/ios/api/reference/Protocols/GADRewardBasedVideoAdDelegate
but i don't find here:
maybe is no more available in newest Admob SDK.
Please try to delete this event, and try to run again.

Try @rastafan 's suggestion as well.

If that doesn't change, it's possible that this part of the plugin is obsolete. If I have time, I will try to update this.

**Comment by ciaoben** [comment]
Thanks for the info guys. I tried everything but I continue to get the test ADS properly. But then, when I switch to the production ad ID I don't get any ads :/

**Comment by tomitank** [comment]
@ciaoben 
Android and iOS same issue?

**Comment by ciaoben** [comment]
@tomitank I am installing Android and will try. Anyway I tried with banner and interstantial ads, and they work. I only receive test ads for rewards. I guess that are no video available yet for my app. 

Is there a way to support mediation (facebook, ecc..) with this plugin? 
thanks


Do you guys have suggestion about mediation?

**Comment by tomitank** [comment]
> Is there a way to support mediation (facebook, ecc..) with this plugin?

not at the moment, but if you are doing a fork, it can be solved based on this:
https://developers.google.com/admob/android/mediation/facebook

**Comment by tomitank** [comment]
please use the new version. and read the new readme
