### ISSUE TITLE
UMP - Why it's not recommended?

### ISSUE THREAD

**Issue by svzi** [tomitank/cordova-plugin-admob-tomitank#5]
Hi @tomitank ,

you mention in the `README.md` that you don't recommend using UMP. Could you please explain why?

Best,
Sven

**Comment by tomitank** [comment]
@svzi 
The error is inside the SDK. If the user tap the "I’ll decide later" button and restart the app, the Google not send the form again. So I didn't spend time with the android version.

**Comment by svzi** [comment]
@tomitank Thanks for your response. I did some research on my own in the meantime and I came to the same conclusion. It was also not possible for me, to re-open the form after the user made a decision and I restarted the app. So I was unable to change the consent state.

Now I fully understand why you didn't recommend it.
