### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by 123dma** [tomitank/cordova-plugin-admob-tomitank#7]
![image](https://user-images.githubusercontent.com/8977954/96750787-c07d5100-13a2-11eb-9c9d-68310a6001b0.png)

Hello Tomitank, congratulations on plugin. I am trying to install the plugin but I am encountering the error.

and after

![image](https://user-images.githubusercontent.com/8977954/96752361-bbb99c80-13a4-11eb-9738-b713ebe4ec6a.png)

Did you know how to install it?

**Comment by svzi** [comment]
@123dma You could try to delete the `platforms`, `plugins` and `node_modules` folders and the file `package-lock.json`. Then try to re-install the plugin.

I could install it and two projects without any issue.

**Comment by tomitank** [comment]
@123dma 
Hi!

The POD may not be installed properly
