### ISSUE TITLE
Black rectangele at the bottom of screen

### ISSUE THREAD

**Issue by cheabkunthea** [tomitank/cordova-plugin-admob-tomitank#8]
<img width="435" alt="Black rectangle" src="https://user-images.githubusercontent.com/16161664/98339641-997b7c00-203e-11eb-9eab-43a719c40c15.png">
Hello,

Plugin worked fine except Black rectangle appears at the bottom of screen.
Please help to solve this. 

Thank you

**Comment by tomitank** [comment]
Hi!
Without ads work fine?
Try to play with overlap:
`admob.banner.config({ id: admobid.banner, overlap: true });`
or
`admob.banner.config({ id: admobid.banner, overlap: false });`

Maybe your design (.css) is not ready for notches.

**Comment by cheabkunthea** [comment]
After adding 
admob.banner.config({ id: admobid.banner, overlap: true });
Now there is no black rectangle
