### ISSUE TITLE
Do I need to make a consent popup?

### ISSUE THREAD

**Issue by DesignerApparelSales** [tomitank/cordova-plugin-admob-tomitank#9]
Hi tomitank, Thanks for your wonderful plugin. 

Do I need to make a consent form to ask the user permission or is that will be done automatic on ios side? If I need to make one, how do I make one? is it just a simple popup asking for permission and what do I do with the users choice? Is there a plugin for that?  Thanks again.

**Comment by tomitank** [comment]
Hi!
that will be done automatic on ios side :)
But you can show extra window befor that with **cordova-plugin-dialogs**

**Comment by DesignerApparelSales** [comment]
Thanks!
